# Site settings
title: Sofware-Villain
description: 'Software Villain'
url: 'https://vic.github.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
